add_newline = false
format = """
$all
ğŸ¦„ """

[directory]
home_symbol = "~"
read_only = "ğŸ”’"
truncate_to_repo = true
truncation_length = 8
truncation_symbol = "â€¦/"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[character]
error_symbol = "[âŒ](bold red) "
success_symbol = "[âœ”ï¸](bold green) "

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ· "

[username]
disabled = false
format = "[$user]($style) "
show_always = false
style_root = "red bold"
style_user = "white"

[hostname]
disabled = false
format = "on [$hostname](red) "
ssh_only = true
trim_at = ".companyname.com"
